# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Arpita Manohar Telkar"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "arpita.telkar@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "209-221-5396"
resume_contact_address:         "San Jose, California"

resume_header_contact_info:     "San Jose, California • 209-221-5396 • arpita.telkar@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p> I'm Arpita Manohar Telkar, a software engineer based in San Jose, CA, with a passion for turning complex challenges into sleek solutions. During my time at KPMG, I boosted data integration efficiency by 60%, using a blend of Java, Spring Boot, and AWS. My personal projects, like an e-commerce engine that cut response times by 40% and an AI chatbot that simplified customer service, reflect my love for innovation.

I'm not just about coding—I also enjoy mentoring junior engineers and collaborating with teams to create something extraordinary. When it comes to technology, I aim to be the problem solver, the person who finds a way forward when others get stuck. I thrive on turning ambitious ideas into reality, and I’m always looking for the next challenge to tackle.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://arpita-telkar.github.io/port-folio/"
 
  resume_linkedin_url:          "https://www.linkedin.com/in/arpita-telkar"

resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
